# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: WildFly Quickstarts CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  Test-build-default-matrix:
    name: BUILD DEFAULT - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: hotspot
    - name: Build Quickstarts provisioned-server profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pprovisioned-server
      shell: bash
    - name: Build Quickstarts bootable-jar profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pbootable-jar
      shell: bash
    - name: Build Quickstarts openshift profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Popenshift
      shell: bash
    - name: Build Quickstarts Release
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'

  Test-build-with-deps-matrix:
    name: BUILD WITH DEPS - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: wildfly/wildfly
        ref: ${{ github.base_ref }}
        path: wildfly
    - uses: actions/checkout@v2
      with:
        repository: wildfly/boms
        ref: ${{ github.base_ref }}
        path: boms
    - uses: actions/checkout@v2
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: hotspot
    - name: Build Server
      run: |
        cd wildfly
        mvn -U -B -fae -DskipTests clean install
      shell: bash
    - name: Get Server Version
      run: |
        cd wildfly
        echo "VERSION_SERVER=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build BOMs with Server Version
      run: |
        cd boms
        mvn -U -B -fae clean install -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - name: Get BOMs Version
      run: |
        cd boms
        echo "VERSION_BOMS=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build Quickstarts provisioned-server profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pprovisioned-server -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ env.VERSION_SERVER }} -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - name: Build Quickstarts bootable-jar profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pbootable-jar -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ env.VERSION_SERVER }} -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - name: Build Quickstarts openshift profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Popenshift -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ env.VERSION_SERVER }} -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - name: Build Quickstarts Release with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ env.VERSION_SERVER }} -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'
