# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: WildFly Quickstarts CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # Use the shared-wildfly-build workflow to have a consistent WildFly build. Note the branch names MUST match what
  # is used in WildFly.
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: ${{ github.base_ref }}
      wildfly-repo: "wildfly/wildfly"

  Test-build-default-matrix:
    name: BUILD DEFAULT - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Quickstarts provisioned-server profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pprovisioned-server
      shell: bash
    - name: Build Quickstarts bootable-jar profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pbootable-jar
      shell: bash
    - name: Build Quickstarts openshift profile
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Popenshift
      shell: bash
    - name: Build Quickstarts Release
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'

  Test-build-with-deps-matrix:
    name: BUILD WITH DEPS - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: wildfly/wildfly
        ref: ${{ github.base_ref }}
        path: wildfly
    - uses: actions/checkout@v4
      with:
        repository: wildfly/boms
        ref: ${{ github.base_ref }}
        path: boms
    - uses: actions/checkout@v4
      with:
        path: quickstarts
    - uses: actions/download-artifact@v3
      with:
        name: wildfly-maven-repository
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf wildfly-maven-repository.tar.gz -C ~
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build BOMs with Server Version
      run: |
        cd boms
        mvn -U -B -fae clean install -Dversion.server=${{ needs.wildfly-build.outputs.wildfly-version }}
      shell: bash
    - name: Get BOMs Version
      run: |
        cd boms
        echo "VERSION_BOMS=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build Quickstarts provisioned-server profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pprovisioned-server -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ needs.wildfly-build.outputs.wildfly-version }} -Dversion.server=${{ needs.wildfly-build.outputs.wildfly-version }}
      shell: bash
    - name: Build Quickstarts bootable-jar profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Pbootable-jar -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ needs.wildfly-build.outputs.wildfly-version }} -Dversion.server=${{ needs.wildfly-build.outputs.wildfly-version }}
      shell: bash
    - name: Build Quickstarts openshift profile with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean package -Popenshift -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ needs.wildfly-build.outputs.wildfly-version }} -Dversion.server=${{ needs.wildfly-build.outputs.wildfly-version }}
      shell: bash
    - name: Build Quickstarts Release with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ needs.wildfly-build.outputs.wildfly-version }} -Dversion.server=${{ needs.wildfly-build.outputs.wildfly-version }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'
